[package]
name = "i-love-hue-rs"
version = "0.1.0"
authors = ["Athir Saleem <noc7c9@gmail.com>"]
edition = "2018"

[dependencies]
yew = "0.11.0"
web_logger = "0.2.0"
log = "0.4.8"
rand = { version = "0.7.3", features = ["stdweb"] }
rand_pcg = "0.2.1"
stdweb = "0.4.20"
